### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by Toubsi** [intuit/sdp#10]
Hi,
really like the library... Android should have something like this official!
 The MIT license says attribution is required. Is this also for binary distribution or only source?
For example if I upload my app in a app store, do I need to attribute?
Because my app does not have a good place for that like about or something.
Also is this project still in development?
Thanks

**Comment by brettweavnet-intuit** [comment]
@Toubsi 

The MIT license does require attribution for binary distribution.  I know, especially for mobile apps, it’s not always easy to find a place to put it.  If there’s an About or anything like that, you could just link to it from there.  You can also just link to the license file in this repo if that is easier.
