### ISSUE TITLE
Intuit/SDP not working - Not Scaling Vertically

### ISSUE THREAD

**Issue by josephroca** [intuit/sdp#104]
Upon library upgrade it seems as if it is views aren't scaling vertically anymore as all components stay the same size vertically for each screen size. Horizontal scaling still works though. Any solutions for this?

**Comment by elhanan-mishraky** [comment]
Can you post an example such that I'll be able to reproduce the issue?

**Comment by josephroca** [comment]
Well before I have you look into this, is this library made to scale height as well as width? I know its based off of 300 width but does the height get scaled as well when screen size changes?
