### ISSUE TITLE
Fractional "sdp" values would be very nice to have.

### ISSUE THREAD

**Issue by ruslan-yanchyshyn-lemberg** [intuit/sdp#106]
Hello!

Nice library!
I have one "feature request": fractional "sdp" values like 0.5 or 1.5 "spd" would be very nice to have.
Please consider adding a bunch of such values.

Thank you!

**Comment by elhanan-mishraky** [comment]
Hello @ruslan-yanchyshyn-lemberg, I think it is a good idea especially for large displays. Good chances that I'll add it for the next release (no ETA yet).
