### ISSUE TITLE
Smaller devices screen not working ?

### ISSUE THREAD

**Issue by kalanidhidev** [intuit/sdp#107]
I have create design and using sdp values, I test in two devices one is Samsung s10 that is 360 * 720 dpi and Samsung xcover 4s is 360 * 512. It always picking the values-sw360 folder. I have set the margin size 32 in Samsung s10 devices and the same value is using xcover also. So the the child layout are broken

**Comment by elhanan-mishraky** [comment]
This issue happens because Android framework did not allow values to be split by the device height but only by the device width.
