### ISSUE TITLE
Display differences have very different values

### ISSUE THREAD

**Issue by theoyuncu8** [intuit/sdp#108]
hello, this idea is really nice, but when I examined the values ​​folder, the values ​​of 390dp and 420dp caught my eye. Since my device is 411dp, it will use 390dp values. but this can really make a big difference. please review the widths I got from real devices

![a52](https://user-images.githubusercontent.com/97362820/198644283-16c3a177-bf11-4be6-8449-4d59d793cca7.jpg)
![j7 prime](https://user-images.githubusercontent.com/97362820/198644300-fcafdf5d-8d84-40b9-b240-2d35633d78eb.jpg)
![note 8 pro](https://user-images.githubusercontent.com/97362820/198644310-7bac1ad8-02cd-4704-bb00-19555587b040.jpg)
![note 8](https://user-images.githubusercontent.com/97362820/198644318-3961c9ba-27e1-44c1-8cde-ee1f14f75c8e.jpeg)
![note 11 pro](https://user-images.githubusercontent.com/97362820/198644323-f71130d1-94b2-49d7-b0c5-bf13eedb0d51.jpeg)
![poco x3 pro](https://user-images.githubusercontent.com/97362820/198644331-2986525f-a952-41fb-8151-2a5c849ba463.jpeg)
![s6 edge](https://user-images.githubusercontent.com/97362820/198644335-99c51533-9ec3-4d95-8a9d-3a54971ab473.jpg)

**Comment by elhanan-mishraky** [comment]
Hello,
This is an inherent issue. I had to balance continuous sizing and memory footprint. Adding more mapping files will improve the continuity of the sizes but will also make a negative impact on the consuming app size.

**Comment by theoyuncu8** [comment]
> 
hello, I would like you to add values ​​such as at least 320dp and 410dp. because 320dp phones are too many in the market and they will use values ​​of 300dp.. that means a huge difference.

also why did you make sw (smallest width)? What is the difference between normal w (width)

And another thing I want to ask is how did you calculate these scalings? i also want to reference for my own device widths
