### ISSUE TITLE
Can you also add the positive values ​​for 320 and 411dp widths?

### ISSUE THREAD

**Issue by theoyuncu8** [intuit/sdp#109]
hello, my question was not fully answered because you closed the topic. There are too many 320 and 411 wide phones on the market and these are; It uses the value at 300dp, which is a width of 320. Could you please add the values ​​320 and 411 as well?

My other question is; why are you using sw? Can't you just use normal w?

My last question is; How did you create these dp values? can you help me?

(https://github.com/intuit/sdp/issues/108)

**Comment by elhanan-mishraky** [comment]
Hello, I'm still not sure about adding more files because of the memory load it creates. However, you should be able to customize the files creation process as I will describe below.
I cannot use w because it is not impacted by screen rotation.
To create the values one just needs to run createSDP task from build.gradle, you can alter line 48 and replace 30 with 10 to get more files.

**Comment by theoyuncu8** [comment]
hello, I don't fully understand the memory load it creates. Can you explain this performance difference? @elhanan-mishraky

**Comment by elhanan-mishraky** [comment]
The mapping files are part of the compiled APK, adding more files means each user will have to download these additional files. For example, if I'll create a file for each 10 dps change in sw instead of 30 dps I currently use, it will create 3X files.

**Comment by theoyuncu8** [comment]
Hello thanks for your reply. If these dp values ​​are not created, it is necessary to create a design for different screens. I do not know how it will affect the application on ram and cpu, you know better and I would be very happy if you share your experience with us.. 

Also, I couldn't solve the createSDP situation. Is there a more detailed information/tutorial about this? the most used phone widths as a result of my research; 300, 320, 360, 374, 384, 390, 410, 440, 460, 490, 510 if this sdp and ssp generation process is something easy can you add these values ​​as well? 
If you could share it with me, I would be very pleased. Thank you very much for your help in advanced
Best regards

**Comment by Gkemon** [comment]
@theoyuncu8 @elhanan-mishraky  I have just fork it. I will try to contribute. please assist me if I face stuck. Can we make a common discussion channel? or something where I can ask help from your side?

**Comment by elhanan-mishraky** [comment]
@Gkemon I've just enabled discussions: https://github.com/intuit/sdp/discussions/111
