### ISSUE TITLE
Any thought on supporting compose?

### ISSUE THREAD

**Issue by yuvaraj119** [intuit/sdp#110]
How can we use this library in compose with different screen sizes.

**Comment by elhanan-mishraky** [comment]
Could you please elaborate? I'm not sure I understand the question.

**Comment by faldujaldeep** [comment]
Hi @yuvaraj119 

This library also supporting for compose and I am using it like below.

For dp resource can use like this: dimensionResource(id = R.dimen._17sdp)

For sp resource can use like this: dimensionResource(id = R.dimen._44ssp).value.sp

**Comment by abdomostafa1** [comment]
@faldujaldeep 
thanks man your comment helped me ❤
