### ISSUE TITLE
sdp is not Working in Tablet and Desktop version

### ISSUE THREAD

**Issue by maninder-techindustan** [intuit/sdp#114]
It is not working in Tablet and Desktop Versions. Please check and solve these issue. Check below Screenshots :
![Screenshot-2](https://github.com/intuit/sdp/assets/110970054/803c8144-60e1-4037-8fd9-ab4f508922b0)
![Screenshot-1](https://github.com/intuit/sdp/assets/110970054/6e07a2e9-d895-44a3-a04b-881f5e878f6c)

**Comment by abdelillahbel** [comment]
Try using **Constraint** **layout** ✔
#111

**Comment by maninder-techindustan** [comment]
> Try using **Constraint** **layout** heavy_check_mark #111

Already use **Constraint Layout**

**Comment by abdelillahbel** [comment]
try using fixed margin size for you back button.

**Comment by maninder-techindustan** [comment]
@abdelillahbel fixed margin is not a actual solution. Its mean sdp not working properly for Desktop and tablet version.

**Comment by abdelillahbel** [comment]
maybe, am net sdp Lib developer but am android developer i just suggested some solutions fror you from my experience.

**Comment by maninder-techindustan** [comment]
@abdelillahbel Thanks
