### ISSUE TITLE
Lag when using layout editor attributes tab

### ISSUE THREAD

**Issue by Wise-394** [intuit/sdp#115]
There will be small delay or lag for 1-2 secs when inputting the sdp values on the layout editor attributes tab 

I'm not entirely sure if the problem is on my pc but its fine and no lags if I'll put the values directly into the XML code

**Comment by elhanan-mishraky** [comment]
@Wise-394 thanks for letting me know. I don't have control over the layout editor but maybe it will be faster with higher memory allocation.
