### ISSUE TITLE
Plz fix size unit dp which causing Accessibility issue in Play console Pre-launch report

### ISSUE THREAD

**Issue by tohedul** [intuit/sdp#116]
Hi, Plz change the size unit from dp to sp in positive_sdps.xml and negative_sdps.xml files. This is causing accessibility issues in Play Console's Pre-launch report. Issue:
`This item's text size unit is dip. Consider specifying the text size in scaled pixels (sp)`

**Comment by elhanan-mishraky** [comment]
Hi, for text sizes you can use [ssp](https://github.com/intuit/ssp), this will do what you asked for.

**Comment by tohedul** [comment]
It would be better if both of them were available in a single dependency(think about that). Btw thank you
