### ISSUE TITLE
How can I use ?

### ISSUE THREAD

**Issue by karopass** [intuit/sdp#12]
Hi ! 
I think this is one of the best library which can help me to solve mystery of set different size of android device. I am developing new application for learning. I have some questions regarding use this library.

1) I need only one Layout Folder or need create like layout_large, layout_small ?
2) I need create Any Value Folder ?
3) It will work from android 15 to android 23 ?

My one of layout xml is below...can You please tell me how can I integrate this library with it ?

`<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    xmlns:app="http://schemas.android.com/apk/res-auto">

    <android.support.v7.widget.CardView

        android:layout_marginTop="4dp"
        android:layout_marginBottom="4dp"
        app:cardElevation="4dp"
        app:cardCornerRadius="6dp"
        android:layout_marginLeft="8dp"
        android:layout_marginRight="8dp"
        android:layout_width="match_parent"
        android:layout_height="wrap_content">

        <LinearLayout
            android:id="@+id/quoteActionView"
            android:clickable="true"
            android:background="?attr/selectableItemBackground"
            android:orientation="horizontal"
            android:layout_width="match_parent"
            android:layout_height="wrap_content">

            <ImageView
                android:visibility="visible"
                android:id="@+id/imageAuthorView"
                android:scaleType="fitXY"
                android:layout_width="@dimen/author_image_size_quoteList"
                android:layout_height="@dimen/author_image_size_quoteList" />
            <TextView
                android:visibility="gone"
                android:id="@+id/textIndxQuote"
                android:padding="8dp"
                android:gravity="center"
                android:background="#444444"
                android:textColor="@android:color/white"
                android:textStyle="bold|italic"
                android:textSize="16sp"
                android:layout_width="48dp"
                android:layout_height="match_parent" />

            <LinearLayout
      		android:layout_margin="8dp"
      		android:orientation="vertical"
      		android:layout_width="match_parent"
     		android:layout_gravity="center"
      		android:layout_height="wrap_content">

                <TextView
                    android:id="@+id/textQuote"
                    android:scrollHorizontally="true"
                    android:maxLines="2"
                    android:textSize="@dimen/quote_text_size_qoteList"
                    android:textStyle="bold"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content" />
                
            </LinearLayout>

        </LinearLayout>

    </android.support.v7.widget.CardView>

</RelativeLayout>`

Thanks

**Comment by elhanan-mishraky** [comment]
Follow the get stared in the readme and add the dependency to build.gradle
