### ISSUE TITLE
 android:layout_width="@dimen/_0sdp"

### ISSUE THREAD

**Issue by ashokbgutta** [intuit/sdp#13]
some time i need to use @dimen/_0sdp but getting   error  like Couldn't resolve resource @dimen/_0sdp

**Comment by elhanan-mishraky** [comment]
Could you please describe the use case?

**Comment by raviteja06** [comment]
@ashokbgutta dude u can use 0dp for that.

**Comment by ashokbgutta** [comment]
at present i am using 0dp only ..but my issue is for 0dsp its showing error..

**Comment by ashokbgutta** [comment]
my use case is  somewhere i am using 0dp for 
<LinearLayout
                   android:layout_width="0dp"
                    android:layout_height="match_parent"
                    android:layout_margin="@dimen/_1sdp"
                    android:layout_weight="1"
                    android:orientation="vertical">

**Comment by elhanan-mishraky** [comment]
As stated above there is no point to support 0 sdp because it will be the same for all screen sizes

**Comment by Nurtaz440** [comment]
Hello i have the same error please help me. Couldn't resolve resource @dimen/_20sdp

My layout:
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    xmlns:tools="http://schemas.android.com/tools"
    android:background="?attr/bgColor"
    tools:context="mening.dasturim.mytaxiexample.main.MainActivity"
    android:orientation="vertical"
    >

    <com.innerdrawer.Ui.InnerDrawer
        android:id="@+id/nav_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:menuItemGravity="top"
        app:menuItemTextColor="@color/white"
        app:menuItemIconColor="@color/white"
        app:closeDrawerOnMenuClick="true"
        app:appBarEnabled="true"
        app:headerInsideMenuList="true"
        app:footerInsideMenuList="true"
        app:headerLayout="@layout/nav_header_main"
        app:footerlayout="@layout/nav_footer_main"
        app:statusBarDark="true"
        app:shrinkValue="0.8"
        app:appbarColor="?attr/bgColor"
        app:appbarTitleTextColor="?attr/textColorBold"
        app:appbarTitleTextSize="10sp"
        app:blurContent="true"
        app:navigationDrawerBackgroundColor="?attr/bgColor"
        app:HamMenuIconTintColor="?attr/textColorBold">

        <include
            android:id="@+id/ll_dashboard"
            layout="@layout/app_bar_dashboard"
            android:layout_width="match_parent"
            android:layout_height="match_parent" />
    </com.innerdrawer.Ui.InnerDrawer>
</LinearLayout>
