### ISSUE TITLE
Cater for larger high density screens

### ISSUE THREAD

**Issue by ochart2** [intuit/sdp#16]
Would you be able to update for larger high density screens?

**Comment by elhanan-mishraky** [comment]
Could you please specify the density you need?

**Comment by ochart2** [comment]
Don't know screen sizes off hand, but assuming it would be for xxdpi and xxxdpi screens?

**Comment by elhanan-mishraky** [comment]
SDP should work for any density.

**Comment by gkaradagan** [comment]
in phone everything is correct however in tablet somewhere is not correct destiny
