### ISSUE TITLE
Fractional values of sdp

### ISSUE THREAD

**Issue by despectra** [intuit/sdp#18]
It would be nice if there were fractional sdp values, e.g. `@dimen/_3pt5sdp` or maybe `@dimen/_3_5sdp` or something like that, because sometimes I want to position my views on layout more precisely

**Comment by trinadhkoya** [comment]
can we have javacode for generating values.xml files for our required dimensions ?

**Comment by elhanan-mishraky** [comment]
Hey guys, sorry for the huge delay... please refer to the build.gradle file and specifically to the createSDP task.
You can play with it and see how to get the desired result.

**Comment by trinadhkoya** [comment]
@despectra Make use of my code 
package com.askthedoctor.asktheveterinarian.service;
import java.math.*;

import java.lang.*;
/**
 * Created by trina on 12/23/2016.
 */

public class SDPFactory {


   public static double positiveMax = 600;
    double negativeMax = 60;


    public static void main(String[] args) {
          String unit = "dp";
         for(double dimen = 330; dimen <= 330 ; dimen = dimen + 1){

             for(double i=1.0; i<=positiveMax; i+=0.1){
                 double ratio = i/300d;
                 double sdp = ratio*dimen;

//                 System.out.print(Math.round(i*100.0)/100.0+"   is completed and value is " +Math.round(sdp*100.0)/100.0+"\n");
                 System.out.println("<dimen name=_"+String.valueOf(Math.round(i*100.0)/100.0)+">" +Math.round(sdp*100.0)/100.0+"</dimen>");
                 System.out.println("END of 330 ");

             }

         }
    }


}

**Comment by trinadhkoya** [comment]
@elhanan-mishraky You did a great job!! It was Aweosome!!.It would be great if you tell us the PSD design Dimensions to support all the Devices .We all had a little doubt ,in order to support all the screens,what wold be the PSD dimensions

**Comment by elhanan-mishraky** [comment]
@trinadhkoya, you can create designs with 300 px screen width. In this case each pixel corresponds to 1 sdp. I will add it to the readme.

**Comment by trinadhkoya** [comment]
is it just because of we started with 300 right ?Any Height in your mind??

**Comment by elhanan-mishraky** [comment]
Yes, it's because the baseline is 300.
