### ISSUE TITLE
Error:(42, 13) Failed to resolve: com.intuit.sdp:sdp-android:1.0.4

### ISSUE THREAD

**Issue by hscharan** [intuit/sdp#23]
Hi, 

I am using Android Studio version 2.2.2. This latest SDP version 1.0.4 is not being worked i.e. it is not being added in the dependency. Please rectify the problem.

**Comment by elhanan-mishraky** [comment]
@hscharan can you try updating Android Studio? I'm working with 2.3 and don't have issues.
