### ISSUE TITLE
How to calculate dp ?

### ISSUE THREAD

**Issue by ashishparmar** [intuit/sdp#26]
Hello, I have used your library and just awesome. but i am confuse in resolution 1600 * 2560 resolution where Height : 1600 and width :2560, So please give me your formula for add dimensions in new resolution.

**Comment by elhanan-mishraky** [comment]
@ashishparmar is it Android TV? What is the specific device?

**Comment by NikiFoD** [comment]
Hi, and thanks for the great lib. I have the same problem. I can't use it for very high resolution phones like this: 
http://www.gsmarena.com/samsung_galaxy_s7_edge-7945.php

**Comment by elhanan-mishraky** [comment]
@NikiFoD - what is the specific issue? How does sdp behaves on this device?

**Comment by NikiFoD** [comment]
@elhanan-mishraky I think it was a wrong report from a user, but I am not sure yet.
Do we need to add the xml files for values-sw1440dp to accomodate this width (1440px)?

**Comment by elhanan-mishraky** [comment]
@NikiFoD I think the lib should work for s7 edge device with no change.
