### ISSUE TITLE
How does it know?

### ISSUE THREAD

**Issue by trinadhkoya** [intuit/sdp#28]
How does it knows?
if i build my app based on 240px based psd?

**Comment by elhanan-mishraky** [comment]
I would rather​ recommend building on 300px screen width  psd. Then 1px maps to 1sdp.

**Comment by trinadhkoya** [comment]
What if I want to support from 240dpi also !!

**Comment by elhanan-mishraky** [comment]
SDP is density independent, it uses dp which is density independent pixels so it's dpi agnostic.
