### ISSUE TITLE
Not working fine

### ISSUE THREAD

**Issue by Smeet123** [intuit/sdp#3]
Try with google nexus 4 - 4.1.1 API 16. 768*1280 320dpi (Genymotion emulator). If I set proper layout sdp that fits in this configuration, then It looks wired and too small in Samsung Galaxy Tab 4, 8".

**Comment by elhanan-mishraky** [comment]
Can you send your layout XML?

**Comment by Smeet123** [comment]
I am using it in https://android-arsenal.com/details/3/1538

Like below:

LabelView label = new LabelView(this);
label.setText("POP");
label.setBackgroundColor(0xff03a9f4);
label.setTargetView(findViewById(R.id.text),
getResources().getDimension(R.dimen._10sdp);,
LabelView.Gravity.LEFT_TOP);

**Comment by matimoto87** [comment]
I have the same issue :(

ImageView ib = new ImageView(this);

                  ib.setImageResource(drawable.del_ico);
                  ib.setLayoutParams(new LinearLayout.LayoutParams(R,dimen._40sdp,R.dimen._40sdp));

**Comment by elhanan-mishraky** [comment]
matimoto87, what is the screen width (in dps/inches) of the screen were you see the issue?

**Comment by matimoto87** [comment]
@elhanan-mishraky:

``DisplayMetrics{density=1.5, width=800, height=480, scaledDensity=1.2750001, xdpi=2117.71428, ydpi=218.49463}

**Comment by elhanan-mishraky** [comment]
matimoto87, what device is it?

**Comment by matimoto87** [comment]
HTC Desire 500. On Nexus 5 with 400 dpi is the same issue.

**Comment by elhanan-mishraky** [comment]
matimoto87, can you try setting the image as a background drawable instead of an image resource?

**Comment by matimoto87** [comment]
Ok, I will check it later. We will be in touch.

**Comment by elhanan-mishraky** [comment]
Smeet123, can you update to sdp version 1.0.2 and see if the issue persists?

**Comment by Smeet123** [comment]
Oh ok sure. Right now i have not that device in which i was testing however
I will try to test it in that device. Thank you so much for keeping the the
library up to date.

It is really very helpful and save lots of time for defining dps for
different device resolutions.

**Comment by matimoto87** [comment]
@elhanan-mishraky there is no difference, if I use background drawable or image resource. There is no difference, if I set ib.setLayoutParams(new LinearLayout.LayoutParams(R.dimen._40sdp,R.dimen._40sdp)); or ib.setLayoutParams(new LinearLayout.LayoutParams(R.dimen._4sdp,R.dimen._4sdp)); The image have still the same size.

I've update sdp library to 1.0.2... How to use programmatically your dimensions? Maybe I am doing something wrong...

**Comment by elhanan-mishraky** [comment]
@matimoto87, you should set it as a background drawable and use the next code for the layout params:
ib.setLayoutParams(new LinearLayout.LayoutParams(getResources().getDimension(R.dimen._40sdp),getResources().getDimension(R.dimen._40sdp)));

**Comment by matimoto87** [comment]
@elhanan-mishraky my master :) now it works perfectly :+1: thanks!!!

**Comment by elhanan-mishraky** [comment]
Seems it's solved, closing it. If you experience this issue again please reopen.
