### ISSUE TITLE
Irregularity in sizing of views on Nexus 6 in Android.

### ISSUE THREAD

**Issue by AayushTaneja** [intuit/sdp#30]
I have a layout containing just an image. I have set its dimensions using `SDP`. When I previewed the layout on `Nexus 6 (6 inch, xxxhdpi)` in the layout preview, the image was in bounds of the screen. But when i used `Google Pixel (5 inch, xxhdpi)` to preview, the image became out of bounds of the screen.
What I expected was the image would be in same proportion irrespective of screen. 

Dimensions of `ImageView` :
layout_width = `@dimen/_300sdp` (which became `390dp` for Nexus 6 and `360dp` for Google Pixel)
layout_height = `@dimen/_450sdp` (which became `585dp` for Nexus 6 and `540dp` for Google Pixel)

I have previewed the same layout with other mid size devices such as `Nexus 5`, `Nexus 4`, `Galaxy Nexus` and the `ImageView` in all these devices goes out of bounds. But in larger devices such as `Nexus 5X`, `Pixel XL` and `Nexus 6P`, the `ImageView` stays inside the screen.

![pixel](https://user-images.githubusercontent.com/31048248/29335315-e1441546-8227-11e7-9f3f-b9ecfc766383.JPG)

![nexus6](https://user-images.githubusercontent.com/31048248/29335303-d3d73e10-8227-11e7-8a98-dcec6923c7b8.JPG)

**Comment by elhanan-mishraky** [comment]
@AayushTaneja - in this case please use:
layout_width = match_parent
layout_height = match_parent

SDP has some approximations for better memory usage, performance and footprint.
