### ISSUE TITLE
Working or not

### ISSUE THREAD

**Issue by rutul089** [intuit/sdp#35]
when ever i try to add dependencies its show error 
`Error:Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.intuit.sdp:sdp-android:1.0.5.
<a href="openFile:C:/Users/xxx/AndroidStudioProjects/xxx/app/build.gradle">Open File</a><br><a href="Unable to resolve dependency for &#39;:app@debug/compileClasspath&#39;: Could not resolve com.intuit.sdp:sdp-android:1.0.5.">Show Details</a>` any solution for this

**Comment by elhanan-mishraky** [comment]
Can you post here your build.gradle?

**Comment by rutul089** [comment]
sorry, i forgot to close this issue.
