### ISSUE TITLE
Not able to select any edit text except username and contact editext field

### ISSUE THREAD

**Issue by vidhit** [intuit/sdp#37]
When i am trying to click on the password editext field then there is no response and the cursor moves on to the contact no edit text field.The only way through which one can access all the edit text fields is through the TAB key.Similarly, i am not able to type anything in the email edit text field as it does not respond to the touch.Can anyone tell me how to make the touch work perfectly?.I am attaching the image of the activity running on the emulator along with the code
![android error](https://user-images.githubusercontent.com/20031546/36173816-3b95cae8-1130-11e8-8feb-817adfc19073.png)

//successregister activity file

<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context="com.example.vidhit.evoletandroid.successregister">

    <TextView
        android:id="@+id/textView3"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_alignParentTop="true"
        android:layout_centerHorizontal="true"
        android:paddingTop="40dp"
        android:textSize="15sp"
        android:textColor="@color/black"
        android:textAllCaps="true"
        android:text="You are successfully registered" />

    <TextView
        android:id="@+id/usr"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_below="@+id/textView3"
        android:paddingTop="40dp"
        android:text="Username :"
        android:textColor="@color/black"
        android:paddingLeft="10dp"/>

    <TextView
        android:id="@+id/pass"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_below="@+id/usr"
        android:paddingTop="40dp"
        android:text="Password :"
        android:textColor="@color/black"
        android:paddingLeft="10dp"/>

    <TextView
        android:id="@+id/em"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_below="@+id/pass"
        android:paddingTop="40dp"
        android:text="Email :"
        android:textColor="@color/black"
        android:paddingLeft="10dp"/>

    <TextView
        android:id="@+id/contact"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_below="@+id/em"
        android:paddingTop="40dp"
        android:text="Contact No :"
        android:textColor="@color/black"
        android:paddingLeft="10dp"/>

    <EditText
        android:id="@+id/usered"
        android:layout_width="200dp"
        android:layout_height="wrap_content"
        android:layout_alignParentEnd="true"
        android:layout_alignParentRight="true"
        android:layout_alignParentTop="true"
        android:paddingTop="83dp" />

    <EditText
        android:id="@+id/passedit"
        android:layout_width="200dp"
        android:focusable="true"
        android:focusableInTouchMode="true"
        android:layout_height="wrap_content"
        android:layout_alignParentEnd="true"
        android:layout_alignParentRight="true"
        android:layout_alignParentTop="true"
        android:paddingTop="141dp" />

    <EditText
        android:id="@+id/emaedit"
        android:layout_width="200dp"
        android:layout_height="wrap_content"
        android:layout_above="@+id/contact"
        android:layout_alignParentEnd="true"
        android:layout_alignParentRight="true"
        android:paddingTop="201dp"
        android:singleLine="true" />

    <EditText
        android:id="@+id/contactsedit"
        android:layout_width="200dp"
        android:layout_height="wrap_content"
        android:layout_alignParentRight="true"
        android:paddingTop="260dp" />

</RelativeLayout>

//Java file

package com.example.vidhit.evoletandroid;

import android.content.Intent;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.widget.EditText;
import android.widget.TextView;

public class successregister extends AppCompatActivity {

    private EditText usern,passwd,emails,cnt_no;
    private TextView muse,mpassword,mem,mcnt_no;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_successregister);
       initialization();
    }

    private void initialization() {

        usern=(EditText)findViewById(R.id.usered);
        passwd=(EditText)findViewById(R.id.passedit);
        emails=(EditText)findViewById(R.id.emaedit);
        cnt_no=(EditText)findViewById(R.id.contactsedit);
        muse=(TextView)findViewById(R.id.usr);
        mpassword=(TextView)findViewById(R.id.pass);
        mem=(TextView)findViewById(R.id.em);
        mcnt_no=(TextView)findViewById(R.id.contact);

        Intent intent=getIntent();
        //String name=intent.getStringExtra("myname");
        Bundle bundle=getIntent().getExtras();
        Bundle bundle1=getIntent().getExtras();
        Bundle bundle2=getIntent().getExtras();
        Bundle bundle3=getIntent().getExtras();
        String name=bundle.getString("myname");
        String pass=bundle1.getString("mypassword");
        String em=bundle2.getString("myemail");
        String contact=bundle3.getString("mycontact");
        usern.setText(name);
        passwd.setText(pass);
        emails.setText(em);
        cnt_no.setText(contact);

    }

}

**Comment by elhanan-mishraky** [comment]
I don't see any reference to sdp here
