### ISSUE TITLE
README with more information

### ISSUE THREAD

**Issue by yograterol** [intuit/sdp#4]
I'm confused because I dont understand as work this tool, with a layout I can support all screens?

Can add an example project with this library?

**Comment by matimoto87** [comment]
Its simple - library "adds" few values xml files. You nedd only to set demensions respectively, f.ex:

            <LinearLayout
            android:layout_width="fill_parent"
            android:layout_height="wrap_content"
            android:orientation="horizontal"
            android:paddingTop="@dimen/_6sdp" (!)
            android:paddingBottom="@dimen/_6sdp" (!) >

or

                <ImageView
                android:layout_width="@dimen/_30sdp" (!)
                android:layout_height="@dimen/_30sdp" (!)
                android:id="@+id/imageView2"
                android:src="@drawable/cal_ico"
                android:layout_gravity="center_vertical|right"
                android:layout_weight="0"
                android:layout_marginRight="10dp" />

**Comment by yograterol** [comment]
good, but I applied this library in my project and with some screen dont work properly, the min sdk is 16 for me.

**Comment by yograterol** [comment]
@matimoto87 with just one layout work for all screen?

**Comment by elhanan-mishraky** [comment]
@yograterol, it's always preferable to think of a different design for tablets. But, if you want you can also create one layout that fits to every screen using the sdp size unit.

**Comment by yograterol** [comment]
@elhanan-mishraky :+1: and how sdp recognizes what dp assign, because when I try multiple screen in Android Studio show the ugly interfaces in differents mobile phones, in runtime not happen that?

**Comment by elhanan-mishraky** [comment]
@yograterol, the sdp size unit is relative to the screen size. The preview should reflect the runtime. Sometimes, due to a bug in Android Sdudio, the preview won't reflect the runtime.

**Comment by yograterol** [comment]
@elhanan-mishraky okidoki, thank u... I will look again.

**Comment by yograterol** [comment]
Work fine!! :+1: I like it!
