### ISSUE TITLE
Does not work to calculate height?

### ISSUE THREAD

**Issue by btow** [intuit/sdp#43]
Is it possible to adapt the library to calculate the height of the view of the layout template?

**Comment by elhanan-mishraky** [comment]
I'm not sure, I used the concept of "sw" folders (e.g. values-sw300dp) which is relative to the screen width. Are you familiar with some similar concept for screen height?
(see https://developer.android.com/training/multiscreen/screensizes.html)

**Comment by btow** [comment]
For example, the values-sh480dp

**Comment by elhanan-mishraky** [comment]
If so, it should be possible. What is the use case that you are trying to solve with this change?

**Comment by btow** [comment]
It is necessary to implement a change in the height of the view, in proportion to the change in the height of the screen. For example, for a screen with a height of 600 dp, the height of the element should be 250 dp, and for a screen with a height of 320 dp - proportionally smaller.

**Comment by elhanan-mishraky** [comment]
Thanks for you research!

**Comment by btow** [comment]
I'm trying to make approximate calculations of the height on the basis of the known width.

**Comment by btow** [comment]
As a basis, I took a table of the lengths of the sides of the screens from [here](http://dolbodub.blogspot.ru/2014/07/blog-post_5.html). I created a directory structure for your sample, into which you put separate files for positive and negative values of width and height in dp, and also the font size in ps. If interested, the project is posted [here](https://github.com/btow/ru.master-scale).

**Comment by elhanan-mishraky** [comment]
Thanks I will review it.
