### ISSUE TITLE
AAPT2 when linking resources gives error

### ISSUE THREAD

**Issue by akhilsreekar** [intuit/sdp#48]
AGPBI: {"kind":"error","text":"error: resource android:attr/foregroundInsidePadding is private.","sources":[{"file":"C:\\Users\\MyPC\\.gradle\\caches\\transforms-1\\files-1.1\\sdp-android-1.0.5.aar\\6ace9734fe0036a609208f5ef2a38545\\res\\values\\values.xml","position":{"startLine":2,"startColumn":4,"startOffset":55,"endColumn":42,"endOffset":93}}],"original":"","tool":"AAPT"}

 Failed to process resources.

**Comment by elhanan-mishraky** [comment]
Hi @akhilsreekar do you have steps to reproduce this issue?

**Comment by Sarosh-Madara** [comment]
I am getting the same issue does anyone got any success.?
Thanks

**Comment by Sarosh-Madara** [comment]
I just updated My complileSdk and targetSdk to 28 
 compileSdkVersion 28
 targetSdkVersion 28

And it worked for me
