### ISSUE TITLE
using for sdk 8

### ISSUE THREAD

**Issue by lilised** [intuit/sdp#5]
how i could use this library for android 2.2 or min sdk 8?! would u plz help me, this library really helped me but i need it for minsdk 8

**Comment by elhanan-mishraky** [comment]
You can clone it and change the minSdk to 8. It works much better for sdk >= 13, but you can try.

**Comment by lilised** [comment]
im sorry but i new to android how could I clone I dont undrestand what u mean, would u plz explain it to me?! tanx

**Comment by elhanan-mishraky** [comment]
[Download](https://github.com/intuit/sdp/archive/master.zip) it, and modify to minSdk in the build.gradle file.
