### ISSUE TITLE
Negative value set

### ISSUE THREAD

**Issue by TheinvinciblePrints** [intuit/sdp#50]
Cannot set negative sdp example (-30dp)

**Comment by TheinvinciblePrints** [comment]
Yes i am (implementation 'com.intuit.sdp:sdp-android:1.0.5')

**Comment by elhanan-mishraky** [comment]
You are right, I will try to find a solution. The obvious solution is to add more negative values to the lib but it will increase the size of the lib for a usecase that is not common.

**Comment by elhanan-mishraky** [comment]
@shehabosama could you please share some details about the use case you are trying to solve?

**Comment by shehabosama** [comment]
> @shehabosama could you please share some details about the use case you are trying to solve?

Thanks @elhanan-mishraky, I just was looking for how to get the sdp negative values and I found it in this closed issue https://github.com/intuit/sdp/issues/95

**Comment by zoraiz12** [comment]
hello sir kindly increase negative value of sdp
