### ISSUE TITLE
Provide support for the latest API level

### ISSUE THREAD

**Issue by ebghrimtech** [intuit/sdp#55]
Hello,
We are currently using your library in one of our application. Actually we need a favour from your side. According to the Google Play Policy, all apps have to provide support for at least API level 26 which is satisfied in your case. We are targeting API level 28. So can you please provide us support for API level 28 in your current repository?

**Comment by elhanan-mishraky** [comment]
@ebghrimtech thanks for letting me know, working on it.

**Comment by elhanan-mishraky** [comment]
@ebghrimtech you can try version 1.0.6 now, please let me know if you have any issues.

**Comment by ebghrimtech** [comment]
Thanks a lot for your immediate action.
We will check it out and report if there are any issues.
