### ISSUE TITLE
Minus DP for view

### ISSUE THREAD

**Issue by AhmedJAbuSada** [intuit/sdp#60]
I want to use your awesome library like "@dimen/_-25dp" for "-25dp", how can I implement this ?!

**Comment by eclectice** [comment]
+1 with the request from @AhmedJAbuSada . I know it is possible to programmatically retrieve the target sdp id and make a negative value from it. But, we want it reflects the actual -ve easily in the layout designer.

**Comment by elhanan-mishraky** [comment]
Use @dimen/_minus25sdp
