### ISSUE TITLE
dimens giving error: Cannot resolve symbol '@dimen/_12sdp' less... (Ctrl+F1)  Inspection info: Validates resource references inside Android XML files.

### ISSUE THREAD

**Issue by zohaib962** [intuit/sdp#63]
dimens in xml giving error: Cannot resolve symbol '@dimen/_12sdp' less... (Ctrl+F1) 
Inspection info: Validates resource references inside Android XML files.

**Comment by djethva89** [comment]
Hello 
I am facing same problem.
<img width="735" alt="Screenshot 2020-05-26 at 10 43 21 AM" src="https://user-images.githubusercontent.com/12165657/82862605-bbc08800-9f3d-11ea-9bf7-21bd10744fea.png">

**Comment by Yashsomalkar** [comment]
implementation 'com.intuit.ssp:ssp-android:1.0.5'
implementation 'com.intuit.sdp:sdp-android:1.0.5'
in your gradle dependencies 
and see the magic :)
