### ISSUE TITLE
Could not find Versions 1.0.4 And 1.0.6

### ISSUE THREAD

**Issue by uzair19** [intuit/sdp#65]
The versions (1.0.4 & 1.0.6) have been removed from the jcenter.

We are using the 1.0.4 in our current production build. And we cannot build the project because there is no such versions avaliable in jcenter.

Please treat this as high priorioty as we have problems build with these versions.

**Comment by elhanan-mishraky** [comment]
You can find all versions here: http://repo1.maven.org/maven2/com/intuit/sdp/sdp-android/

**Comment by elhanan-mishraky** [comment]
@uzair19 did my previous comment help you?

**Comment by uzair19** [comment]
@elhanan-mishraky Sorry for the late reply, I was using gradle in the offline mode until this issue could be fixed. After seeing your comment I removed the check of 'offline mode' and tried again. Its working perfectly fine now.

Thanks
