### ISSUE TITLE
using createSDP

### ISSUE THREAD

**Issue by Yambottle** [intuit/sdp#66]
Hey guys, sorry for the huge delay... please refer to the build.gradle file and specifically to the createSDP task.
You can play with it and see how to get the desired result.

_Originally posted by @elhanan-mishraky in https://github.com/intuit/sdp/issues/18#issuecomment-267933518_

Hi Elhanan, I'm facing the same issue of trying to use fractional sdp. You mentioned before to refer the createSDP and create any kinds of sdp by ourself. I actually understand the logic written by JAVA within build.gradle, but I'm not very good at Gradle, I really don't know how to embed them into my project. Could you please provide me more detailed instructions? Or links also work, Thanks!

**Comment by Yambottle** [comment]
I'm here to close my issue.
Last time, the reason why I failed to embed is because I didn't manually run the task on gradle.
<img width="936" alt="Screen Shot 2019-04-07 at 14 27 37" src="https://user-images.githubusercontent.com/31813282/55688721-642e1a00-5941-11e9-801a-44edd7940415.png">

**Comment by Yambottle** [comment]
Still, want to appreciate the author @elhanan-mishraky . This trick is awesome!

**Comment by theoyuncu8** [comment]
hello I was unable to run createSDP. Please help gradle side menu is empty.. my location: https://github.com/intuit/sdp/issues/109


It would also be nice if you could generate and post the width values ​​I need for me. If it is possible.. ,

300, 320, 360, 374, 384, 390, 410, 440, 460, 490, 510

**Comment by yambottle** [comment]
> theoyuncu8

Sorry, I've been working with Android for a really long time and I don't have the environment anymore, but from what I can still recall, you need to either click a button or right click the task to manually run `createSDP`. I'm not sure why your side menu is empty tho...

**Comment by elhanan-mishraky** [comment]
@theoyuncu8 you can also try to run it with Android Studio from build.gradle, just click the green arrow on the left.
<img width="443" alt="image" src="https://user-images.githubusercontent.com/984388/200563286-922fed37-d8ed-4348-a74b-5ff6a148b7b6.png">

**Comment by theoyuncu8** [comment]
![image](https://user-images.githubusercontent.com/97362820/200567172-438b7cf0-a996-4ca5-81ad-516d020731f0.png)

First of all, thanks for your interest and help.

but I couldn't run it. i.e. it works fine but it doesn't create files..
what should i do in this situation?

**Comment by theoyuncu8** [comment]
@elhanan-mishraky  hello, can you share your information about performance? I'm very curious about your thoughts and experiences (ram, cpu etc)

**Comment by elhanan-mishraky** [comment]
I don't think it will impact ram/cpu, I assume it will just add a few hundred KB to the APK.

**Comment by theoyuncu8** [comment]
> 

if it will only affect the size we can pull the dp max to 300dp and use it for every 10 widths
