### ISSUE TITLE
Easy 1 to 1 mapping

### ISSUE THREAD

**Issue by Myk-da-Beast** [intuit/sdp#67]
I see in the wiki it says "For easy mapping of designs to sdp units, one can create designs with 300 pixels screen width - in this case each pixel in the design corresponds to 1 sdp." But it does not mention a height? Does 300 pixels screen width work with every height?

**Comment by GauravBharadia** [comment]
this should work when we give @dimen/_38sdp height and width to make a square but when we change resolution of mobile screen it does not work properly
