### ISSUE TITLE
sdp not supporting few devices

### ISSUE THREAD

**Issue by rachit011** [intuit/sdp#68]
Many Samsung devices(Samsung s4 and Samsung note 3 tested) and also some standard devices(Nexus 5, Pixel Series tested)isn't supported by this library. Please try to fix this.

**Comment by elhanan-mishraky** [comment]
What do you mean by not supported? Is it crashing? Some other problem?

**Comment by elhanan-mishraky** [comment]
Closing as I couldn't get a response.
