### ISSUE TITLE
Latest dependency not working with latest android studio version.

### ISSUE THREAD

**Issue by ArbazGitHub** [intuit/sdp#70]
i just update my android studio with 3.4.1 version and i tried to open existing project with have 
this dependency **implementation 'com.intuit.sdp:sdp-android:1.0.5'** after gradle sync i got bellow error  **Failed to resolve: com.intuit.sdp:sdp-android:**1.0.5 i also try with latest version of dependency still got same error,

but i am surprised when i change dependency   with older version its working fine i don't know why?

how can i use latest version of SDP ?

**Comment by elhanan-mishraky** [comment]
Checking it now.

**Comment by elhanan-mishraky** [comment]
I couldn't reproduce this issue, can you try again to rebuild?
