### ISSUE TITLE
0.5 ... 15.5

### ISSUE THREAD

**Issue by Trupen** [intuit/sdp#71]
Please update your library to 0.5...15.5 because its most importance in designing

**Comment by Zhuinden** [comment]
What do you mean?

**Comment by Trupen** [comment]
Your library not providing sdp with floating point as like @dimen/1.5sdp...

**Comment by elhanan-mishraky** [comment]
It's a tradeoff, as adding fractional sdps will increase the size of the library. However, you can create your fork with fractional sdps.
