### ISSUE TITLE
it's not support 0.5 values 

### ISSUE THREAD

**Issue by vikramvikraanth** [intuit/sdp#74]
when i was design it's not support 0.5 value like
        android:padding="@dimen/_10.5sdp"
that values can you please consider my issue

**Comment by elhanan-mishraky** [comment]
I can add it if it will a popular request.

**Comment by abservetechTech** [comment]
it  still not updated yet, check below point


when i was design it's not support 0.5 value like
android:padding="@dimen/_10.5sdp"
that values can you please consider my issue
