### ISSUE TITLE
SDP for new Sony Xperia 1 - 21:9 aspect ratio

### ISSUE THREAD

**Issue by iashu90** [intuit/sdp#75]
@elhanan-mishraky  I knew SDP works respectively with SW ( Smallest Screen 

width ). In my case with the new device Sony Xperia 1, the height is too tall. How to scale the views equally using SDP? Any workaround to support my use-case? 

SW for this device is 411

### **Expected - Pixel**
<img width="467" alt="Expected - Pixel" src="https://user-images.githubusercontent.com/13761274/64468237-f85e0200-d0d6-11e9-8047-a49ec0a4805c.png">

### **Unexpected - Sony Xperia 1**
<img width="502" alt="Unexpected - Sony Xperia 1" src="https://user-images.githubusercontent.com/13761274/64468238-f85e0200-d0d6-11e9-8e70-74a14c8e6757.png">

**Comment by elhanan-mishraky** [comment]
You can place a view below the 'Next' button with layout_weight=1 and layout_height=0. It will push it up.
