### ISSUE TITLE
[QUESTION] Should we use it?

### ISSUE THREAD

**Issue by Cand3h** [intuit/sdp#77]
Not really an issue, I just need some info about sdp.

Question:
This library scales great from the smallest screen to the largest on the tablets while keeping the dimensions. Does Google recommend doing it like this, or do they want to use it without sdp like it's shown in the provided example of the library?

**Comment by elhanan-mishraky** [comment]
@Cand3h, this is a very good question, however I didn't see any official instruction from Google.
