### ISSUE TITLE
Using in java class

### ISSUE THREAD

**Issue by siddharth9470** [intuit/sdp#79]
is there a way to use sdp programmatically in .java class

**Comment by siddharth9470** [comment]
I have a use case where i have to create a method that will take integer as a parameter and will return value in sdp, here is my method

private int getDimensionInSDP( int value) { 
       String dimenString = "R.dimen._" + value + "sdp";
       return (int) getResources().getDimension(Integer.parseInt(dimenString));
}

But its giving an error. So my question is, is there a way to do so ?

**Comment by elhanan-mishraky** [comment]
int valueInPixels = (int) getResources().getDimension(R.dimen._10sdp)
