### ISSUE TITLE
Negetive Values beyond 60sdp

### ISSUE THREAD

**Issue by khkarthik** [intuit/sdp#80]
Hey Team,

i need values like minus220 , how do i get that ?

**Comment by elhanan-mishraky** [comment]
You will have to clone the lib edit https://github.com/intuit/sdp/blob/master/sdp-android/build.gradle and create a custom build. Uncomment "preBuild.dependsOn createSDP", update negativeMax to 220 and then build again. Then you will have your custom sdp build and you can replace the regular sdp lib with your custom sdp build.
