### ISSUE TITLE
The device has less than 300 DPI then?

### ISSUE THREAD

**Issue by KD-Azilen** [intuit/sdp#84]
My testing device Samsung Galaxy J7 - 2016 have 267dpi you can check more information on the attached screenshot.
Because baseline is 160dpi and currently in this lib 300dpi showing as a baseline if I'm wrong then please correct me.
![device-2020-08-21-102829](https://user-images.githubusercontent.com/68549009/90853917-1e88ba80-e399-11ea-9a60-58ffb30c8811.png)

**Comment by Fahad-Follow** [comment]
Please update on this as same issue occurs while testing on samsung J7 2016

**Comment by elhanan-mishraky** [comment]
The lib is dpi (dots per inch) independent as it is based on dp sizes and the baseline is 300dp sw (smallest-width) which is smaller than the sw of the device you specified.
