### ISSUE TITLE
How can I get sdp value from an integer which indicates size in sdp?

### ISSUE THREAD

**Issue by nmghelani** [intuit/sdp#91]
Hey, @elhanan-mishraky Loved your library.
I am in a situation where I'm changing view size by seekbar. So, 
If seekbar value is 20, I want to use _20sdp. If seekbar value is 40, I want to use _40sdp.
Is there any way to overcome this situation?

**Comment by elhanan-mishraky** [comment]
Can this code help?
int valueInPixels = (int) getResources().getDimension(R.dimen._10sdp)

**Comment by nmghelani** [comment]
No @elhanan-mishraky
because the problem is that I don't know xx value. It's dynamic. 
If I know that I want 10sdp then I can use getDimension(R.dimen._10sdp) but that value (i.e 10 in this case) itself is dynamic.

**Comment by elhanan-mishraky** [comment]
I hope this can help you: https://stackoverflow.com/questions/2685345/getting-value-of-public-static-final-field-property-of-a-class-in-java-via-refle

**Comment by nmghelani** [comment]
Thanks for the reference. I tried it but it wasn't helpful as I want to get field value from dimens.xml. The reference you shared is to get field value from the R class. I don't know how it works but thanks for your help. I'll look into it more.

**Comment by jughoor** [comment]
@nmghelani @elhanan-mishraky did you find any for this issue ?
