### ISSUE TITLE
UI is overlapping in one of the emulator and physical Samsung devices 

### ISSUE THREAD

**Issue by bipinvaylu** [intuit/sdp#94]
I am using this lib for a long and it working smoothly but today I am seeing UI overlapping issues in the following devices. Please check out screenshots.

#### Devices display details:
- 1st:   Pixel XL (emulator) - 1080x1920 (420 dpi)
- 2nd: Samsung A51 (emulator) - 1080x2400 (xxhdpi) - Overlapping isuse
- 3rd: Nokia 6.1 plus (Physical device) - 1080x2280 (432 ppi)
- Other: Samsung M01 (Physical device) - 720x1520 (294 ppi) - Overlapping issue same as 2nd one in screenshot 

<img width="1126" alt="Screenshot 2021-09-15 at 12 46 19 PM" src="https://user-images.githubusercontent.com/717062/133389326-8953d6dd-10b9-414f-9569-f37fbae91d6f.png">

#### layout code:
- chat_media_list.xml
```
<?xml version="1.0" encoding="utf-8"?>
<androidx.recyclerview.widget.RecyclerView xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/mediaItemRecyclerView"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:orientation="vertical"
    android:layout_gravity="center_horizontal"
    app:layoutManager="androidx.recyclerview.widget.GridLayoutManager"
    app:spanCount="3"
    tools:itemCount="10"
    android:clipToPadding="false"
    android:padding="@dimen/_1sdp"
    tools:listitem="@layout/item_chat_media"
    tools:visibility="visible" />
```
- item_chat_media.xml
```
<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/chatGridMediaItem"
    android:layout_width="@dimen/chat_media_item_width"
    android:layout_height="@dimen/chat_media_item_height"
    android:layout_margin="@dimen/_2sdp"
    android:clickable="true"
    android:foreground="?android:attr/selectableItemBackground">

    <ImageView
        android:id="@+id/chatMediaImageView"
        android:layout_width="0dp"
        android:layout_height="0dp"
        android:background="@drawable/default_item_place_holder"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent" />

    <ImageView
        android:id="@+id/chatMediaPlayImageView"
        android:layout_width="@dimen/_24sdp"
        android:layout_height="@dimen/_24sdp"
        android:background="@drawable/ic_circle_background"
        android:padding="@dimen/_4sdp"
        android:src="@drawable/exo_icon_play"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent" />

</androidx.constraintlayout.widget.ConstraintLayout>

```
- dimensions.xml
```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    
    <dimen name="chat_media_item_width">@dimen/_100sdp</dimen>
    <dimen name="chat_media_item_height">@dimen/_100sdp</dimen>

</resources>
```

I am not sure what I am missing here but there might be something that I am doing wrong. Let me know if you need any other details.

**Comment by rodobe** [comment]
Hi, try changing the android:layout_margin="@dimen/_2sdp" in the item_chat_media.xml file for:

android:layout_marginTop="@dimen/_2sdp"
android:layout_marginBottom="@dimen/_2sdp"
android:layout_marginStart="@dimen/_2sdp"
android:layout_marginEnd="@dimen/_2sdp"

Second: I see you are using 
    android:layout_width="@dimen/chat_media_item_width"
    android:layout_height="@dimen/chat_media_item_height"
    
This will adjust the size in every device but if the size is bigger than the screen u will have overlapping problems no matter is you are using sdp o ssp.

Example if you have a device width of 300 and your item even using sdp have width 100 if you put 3 items you will have no space between them. 

For preventing that use width match_parent  in your item and his child views width=0dp 

Let me know if it works.

**Comment by elhanan-mishraky** [comment]
Closing as this thread is inactive.
