### ISSUE TITLE
Different text size on landscape and portrait

### ISSUE THREAD

**Issue by skauss** [intuit/sdp#96]
Thank you for building this package.

On a Tablet I need different screen sizes for portrait and landscape mode.
Did you get the res/values by trail and error ?
Or you have an script/program to calculate them ?
If you have one program please publish it. 

The landscape dimen need to be in values-swXXX-land directories.

Regards
Stephan

**Comment by elhanan-mishraky** [comment]
Yes, the code is here: https://github.com/intuit/sdp/blob/master/sdp-android/build.gradle. You'll have to uncomment line 80, preBuild.dependsOn createSDP. Please let me know how it goes as I didn't run it for long time now.
