### ISSUE TITLE
how we use sdp for dynamic layout

### ISSUE THREAD

**Issue by Srishti-Chetu** [intuit/sdp#97]
when we are setting dynamic image view on linear layout we need to give some top difference, how we use sdp

**Comment by elhanan-mishraky** [comment]
You can follow the [example](https://github.com/intuit/sdp/blob/master/sdp-android/src/main/res/layout/sdp_example.xml).

**Comment by Srishti-Chetu** [comment]
> when we are setting dynamic image view on linear layout we need to give some top difference, how we use sdp

w

> You can follow the [example](https://github.com/intuit/sdp/blob/master/sdp-android/src/main/res/layout/sdp_example.xml).

we need to add image dynamically by java code
